---

- hosts: spine
  strategy: free
  gather_facts: false
  roles:
    - role: spine

- hosts: leaf
  strategy: free
  gather_facts: false
  roles:
    - role: leaf

#- hosts: all
  #tasks:
  #  - name: save config
  #    nxos_save_config: host={{ inventory_hostname }}

