- hosts: all
  gather_facts: False
  strategy: free

  tasks: 
    - name: Disable features which removes config
      cisco.nxos.nxos_feature:
        feature: '{{ item.feature }}'
        state: disabled
      with_items: '{{ vxlan_features }}'
    
    - name: Disable EVPN overlay
      nxos_evpn_global:
        nv_overlay_evpn: false

    - name: Configuring Distributed Anycast Gateway MAC Address on Leaves
      nxos_config:
        lines:
          - no fabric forwarding anycast-gateway-mac 0000.0000.000A
    
    - name: Delete Tenant VRF
      nxos_vrf:
        name: '{{ item.name }}'
        state: deleted
      with_items: '{{ tenant_a_vrf_config }}'

    - name: Configuring Host Facing Interfaces as L2 
      nxos_l2_interfaces:
        config: 
          - name: '{{item.name}}'
        state: deleted
      with_items: '{{ host_facing_ifaces }}'

    - name: Delete loopbacks
      cisco.nxos.nxos_interfaces:
        config:
          - name: loopback 0
          - name: loopback 1
        state: deleted
      ignore_errors: yes

    - name: Delete interface config
      cisco.nxos.nxos_interfaces:
        config:
          - name: '{{item.name}}'
        state: deleted 
      with_items: 
        - '{{ fabric_ifaces }}'
        - '{{ host_facing_ifaces }}'

    - name: Delete VLANs
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: '{{ item.vlan_id }}'
            name: '{{ item.name }}'
        state: deleted
      with_items: '{{ tenant_a_vlan_to_vni }}'

    # - name: Saving Configuration
    #   nxos_config:
    #     save_when: changed
