- hosts: all
  gather_facts: True
  strategy: free

  tasks: 
      # Needed to add this before disabling the fabric forwarding feature
      # otherwise it's not cleaned up correctly
    - name: Remove Distributed Anycast Gateway MAC Address on Leaves
      nxos_config:
        lines:
          - no fabric forwarding anycast-gateway-mac 
      register: result
      fail:
        msg: "{{ result.stderr }}"
      when: "'FAILED' in result.stderr"
      ignore_errors: yes
      
    # Needed to add this as the loopback interfaces were not being deleted 
    # and I don't have time to troubleshoot
    - name: Delete Loopback Interfaces
      nxos_config:
        lines:
          - no interface loopback 0 
          - no interface loopback 1
      ignore_errors: yes

    - name: Disable features which removes config
      cisco.nxos.nxos_feature:
        feature: '{{ item.feature }}'
        state: disabled
      with_items: '{{ vxlan_features }}'
      ignore_errors: yes

    - name: Disable EVPN overlay
      nxos_evpn_global:
        nv_overlay_evpn: false
      ignore_errors: yes

    - name: Delete Tenant VRF
      nxos_vrf:
        name: '{{ item.name }}'
        state: absent
      with_items: '{{ tenant_a_vrf_config }}'
      when: tenant_a_vrf_config is defined
      ignore_errors: yes

    - name: Delete interface config
      cisco.nxos.nxos_interfaces:
        config:
          - name: '{{item.name}}'
        state: deleted 
      with_items: 
        - '{{ fabric_ifaces }}'
      when: fabric_ifaces is defined
      ignore_errors: yes
    
    - name: Delete interface config
      cisco.nxos.nxos_interfaces:
        config:
          - name: '{{item.name}}'
        state: deleted 
      with_items: 
        - '{{ host_facing_ifaces }}'
      when: host_facing_ifaces is defined
      ignore_errors: yes

    - name: Delete interface config
      cisco.nxos.nxos_interfaces:
        config:
          - name: '{{item.name}}'
        state: deleted 
      with_items: 
        - '{{ loopback_ifaces }}'
      when: loopback_ifaces is defined
      ignore_errors: yes

    - name: Delete VLANs
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: '{{ item.vlan_id }}'
            name: '{{ item.name }}'
        state: deleted
      with_items: '{{ tenant_a_vlan_to_vni }}'
      when: tenant_a_vlan_to_vni is defined
      ignore_errors: yes

    # - name: Saving Configuration
    #   nxos_config:
    #     save_when: changed
