- hosts: all
  vars:
    commands:
      #- "show version"
      - "show ip route"

  tasks:
  - name: run show version on remote devices
    cisco.nxos.nxos_command:
      commands: "{{ item }}"
    register: echo
    with_items: "{{ commands }}"

  - name:  STDOUT - show version
    debug: 
      msg: "{{ item.stdout }}"
    with_items: "{{ echo.results }}"
    loop_control:
      label: "{{ item.item }}"