- hosts: all
  gather_facts: False
  strategy: free
  vars:
    tag: ""
    commands:
      - command: show version
        tags: 
        - mgmt
      - command: show module
        tags: 
        - mgmt
      - command: show interface brief
        tags: 
        - interface
        - int
      - command: show ip interface brief
        tags: 
        - interface
        - int
        - l3
      - command: show ip route
        tags: 
        - l3
        - routing
      - command: show ip route bgp vrf tenant_a
        tags: 
        - l3
        - routing
        - bgp
      - command: show vxlan
        tags: 
        - vxlan
      - command: show l2route evpn mac evi 10
        tags: 
        - vxlan
      - command: show l2route evpn mac-ip evi 10
        tags: 
        - vxlan
      - command: show bgp l2vpn evpn
        tags: 
        - vxlan
        - bgp
      - command: show bgp l2vpn evpn vni-id 100010
        tags: 
        - vxlan
        - bgp
      - command: show bgp l2vpn evpn neighbor
        tags: 
        - vxlan
        - bgp
      - command: show bgp l2vpn evpn neighbor 10.201.1.1 routes
        tags: 
        - vxlan
        - bgp
      - command: show bgp l2vpn evpn neighbor 10.201.1.1 routes
        tags: 
        - vxlan
        - bgp
      - command: show nve peers
        tags: 
        - vxlan
        - nve
      - command: show bgp internal nve-peer-vni
        tags: 
        - vxlan
        - bgp
        - nve
      - command: interface nve 1
        tags: 
        - vxlan
        - nve
        - interface
        - int
      - command: show nve vxlan-params
        tags: 
        - vxlan
        - nve
      - command: show nve internal platform interface nve1 detail
        tags: 
        - vxlan
        - nve
        - interface
        - int
      - command: show nve peer detail
        tags: 
        - vxlan
        - nve
      - command: show bgp internal evi 100010
        tags: 
        - vxlan
        - bgp
        - evi

  tasks:
  - name: IF TAG PROVIDED - Run show commands based on tag
    set_fact:
      commands: "{{ commands | json_query(query) }}"
    vars:
      query: "[?tags.contains(@, '{{ tag }}')].command"
    when: tag != ""
  
  - name: IF NO TAG PROVIDED - Run all show commands
    set_fact:
      commands: "{{ commands | json_query(query) }}"
    vars:
      query: "[].command"
    when: tag == ""

  - name: Run show commands on remote devices
    cisco.nxos.nxos_command:
      commands: "{{ item }}"
    ignore_errors: yes
    register: echo
    with_items: "{{ commands }}"

  - name:  STDOUT - Verificaiton Commands
    debug: 
      msg: "{{ item.stdout_lines[0] }}"
    ignore_errors: yes
    with_items: "{{ echo.results }}"
    loop_control:
      label: "{{ item.item }}"