- hosts: all
  gather_facts: False
  strategy: free
  vars:
    tag: ""
    commands:
      - command: show version
        tags: 
        - mgmt
      - command: show module
        tags: 
        - mgmt
      - command: show interface brief
        tags: 
        - underlay
      - command: show ip interface brief
        tags: 
        - underlay
      - command: show ip ospf neighbors 
        tags: 
        - underlay
      - command: show ip route ospf-OSPF_UNDERLAY_NET 
        tags: 
        - underlay
      - command: show ip pim interface brief 
        tags: 
        - multicast
      - command: show ip pim rp 
        tags: 
        - multicast
      - command: show ip bgp neighbors
        tags: 
        - control
      - command: show bgp l2vpn evpn summary 
        tags: 
        - control
      - command: show fabric forwarding internal topo-info
        tags: 
        - control
      - command: show ip arp suppression-cache detail
        tags: 
        - control
      - command: show vxlan
        tags: 
        - overlay
      - command: show vxlan interface
        tags: 
        - overlay
      - command: show nve peers
        tags: 
        - overlay
      - command: show mac address-table vni 100010
        tags: 
        - l2vni
      - command: show bgp l2vpn evpn vni-id 100010
        tags: 
        - l2vni
      - command: show l2route evpn mac evi 10
        tags: 
        - l2vni
      - command: show l2route evpn mac-ip evi 10
        tags: 
        - l2vni
      - command: show bgp l2vpn evpn vni-id 100999
        tags: 
        - l3vni
      - command: show l2route evpn mac evi 999
        tags: 
        - l3vni
      - command: show ip route bgp vrf tenant_a
        tags: 
        - l3vni
      - command: show bgp l2vpn evpn neighbor 10.201.1.1 routes
        tags: 
        - l3vni

  tasks:
  - name: IF TAG PROVIDED - Run show commands based on tag
    set_fact:
      commands: "{{ commands | json_query(query) }}"
    vars:
      query: "[?tags.contains(@, '{{ tag }}')].command"
    when: tag != ""
  
  - name: IF NO TAG PROVIDED - Run all show commands
    set_fact:
      commands: "{{ commands | json_query(query) }}"
    vars:
      query: "[].command"
    when: tag == ""

  - name: Run show commands on remote devices
    cisco.nxos.nxos_command:
      commands: "{{ item }}"
    ignore_errors: yes
    register: echo
    with_items: "{{ commands }}"

  - name:  STDOUT - Verificaiton Commands
    debug: 
      msg: "{{ item.stdout_lines[0] }}"
    ignore_errors: yes
    with_items: "{{ echo.results }}"
    loop_control:
      label: "{{ item.item }}"