---

  nxos_provider:
    username: "{{ user }}"
    password: "{{ pwd }}"
    transport: nxapi
    host: "{{ inventory_hostname }}"


  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: "nv overlay" }
  - { feature: pim }

  l3_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }

  ospf_process_id: Underlay

  ospf_area: 0
  
  asn: 64520

  address_families:
  - { afi: l2vpn, safi: evpn }
  
  bgp_neighbors:
  - { remote_as: 64520, neighbor: 10.101.1.1, update_source: Loopback0 }
  - { remote_as: 64520, neighbor: 10.101.1.2, update_source: Loopback0 }

  s1_loopback: 10.201.1.1
  s2_loopback: 10.201.1.2

  rp_address: 1.2.3.4
