- name: Enabling necessary features
  nxos_feature:
    feature: '{{ item.feature }}'
    state: '{{ item.state }}'
  with_items: '{{ vxlan_features }}'

- name: Enabling EVPN overlay
  nxos_evpn_global:
    nv_overlay_evpn: true

- name: Creating Loopback interfaces to be used as Router-ID and VTEP-ID
  nxos_interfaces:
    config:
      - name: loopback 0
        enabled: yes
  ignore_errors: yes

- name: Assigning IP Addresses to the Loopback interfaces
  nxos_l3_interfaces:
    config:
      - name: '{{ item.name }}'
        ipv4: 
          - address: '{{ item.ipv4 }}'
  with_items: '{{ loopback_ip }}'

- name: Configuring Host Facing Interfaces as L2 
  nxos_interfaces:
    config: 
      - name: '{{item.name}}'
        enabled: yes
  with_items: '{{ host_facing_ifaces }}'

- name: Configuring Host Facing Interfaces as L2 
  nxos_l2_interfaces:
    config: 
      - name: '{{item.name}}'
        mode: access
        access: 
          vlan: '{{item.vlan_id}}'
  with_items: '{{ host_facing_ifaces }}'

- name: Configuring Spine Facing Interfaces as L3 and with Jumbo MTU
  nxos_interfaces:
    config:
      - name: '{{item.name}}'
        mode: layer3
        mtu: '9216'
        enabled: yes
  with_items: '{{ spine_facing_ifaces }}'

- name: Configuring Spine Facing interfaces with IP Unnumbered Parameters
  nxos_config:
    lines:
      - medium p2p
      - ip unnumbered loopback 0
    parents:
      - 'interface {{item.name}}'
  with_items: '{{ spine_facing_ifaces }}'

- name: Creating OSPF Process 'OSPF_UNDERLAY_NET'
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
        - process_id: OSPF_UNDERLAY_NET
          router_id: '{{ router_id }}'

- name: Configuring Spine Facing Interfaces as OSPF p2p interfaces
  nxos_config:
    lines:
      - ip ospf network point-to-point
    parents:
      - 'interface {{ item.name }}'
  with_items: '{{ spine_facing_ifaces }}'

- name: Assigning Interfaces to the OSPF Process
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: '{{ item.name }}'
        address_family: 
          - afi: ipv4
            processes: 
              - process_id: OSPF_UNDERLAY_NET
                area:
                  area_id: 0
  with_items:
    - '{{ spine_facing_ifaces }}'
    - '{{ loopback_ifaces }}'

- name: Configuring PIM RP Addresses
  nxos_pim_rp_address:
    rp_address: '{{ rp_address }}'
    state: present

- name: Configuring PIM Sparse Mode on L3 interfaces
  nxos_pim_interface:
    interface: '{{ item.name }}'
    sparse: yes
  with_items:
    -  '{{ spine_facing_ifaces}}'
    -  '{{ loopback_ifaces }}'

- name: Creating BGP Process
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: 64520
      router_id: '{{ router_id }}'
      neighbors:
        - neighbor_address: '{{ item.neighbor }}'
          remote_as: 64520
          update_source: Loopback0
  with_items: '{{ bgp_spine_neighbors }}'

- name: Enabling L2VPN EVPN Address-Family Parameters For Spine Neighbors
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config: 
      as_number: '64520'
      neighbors:
        - neighbor_address: '{{ item.neighbor }}'
          address_family:
            - afi: l2vpn
              safi: evpn
              send_community:
                both: yes
              route_reflector_client: no
            - afi: ipv4
              safi: unicast
              send_community:
                both: yes
              route_reflector_client: no
  with_items: '{{ bgp_spine_neighbors }}'

- name: Creating VLANs and Mapping Them to VXLAN VNIs
  nxos_vlan:
    vlan_id: '{{ item.vlan_id }}'
    name: '{{ item.name }}'
    mapped_vni: '{{ item.mapped_vni }}'
  with_items: '{{ tenant_a_vlan_to_vni }}'

- name: Creating Tenant VRF and Mapping it to L3VNI
  nxos_vrf:
    name: '{{ item.name }}'
    vni: '{{ item.vni }}'
    rd: auto
    state: present
  with_items: '{{ tenant_a_vrf_config }}'

- name: Configuring AF specific settings for Tenant VRF
  nxos_vrf_af:
    vrf: '{{ item.name }}'
    afi: ipv4
    route_target_both_auto_evpn: yes
  with_items: '{{ tenant_a_vrf_config }}'

- name: Creating VXLAN Tunnel Interface
  nxos_interfaces:
    config:
      - name: nve1
        enabled: no

- name: Configuring VXLAN Tunnel Interface for MP-BGP EVPN Control Plane
  nxos_vxlan_vtep:
    interface: nve1
    host_reachability: yes
    source_interface: loopback0

- name: Adding L2 VNIs to VXLAN Tunnel Interface
  nxos_vxlan_vtep_vni:
    interface: nve1
    vni: '{{ item.vni }}'
    multicast_group: '{{ item.mcast_grp }}'
    suppress_arp: no
  with_items: '{{ tenant_a_l2_vni }}'

- name: Adding L3 VNI to VXLAN Tunnel Interfaces
  nxos_vxlan_vtep_vni:
    interface: nve1
    vni: '{{ item.vni }}'
    assoc_vrf: yes
  with_items: '{{ tenant_a_l3_vni }}'

- name: Enabling NVE VXLAN tunnel interface
  nxos_interfaces:
    config:
      - name: nve1
        enabled: yes
  ignore_errors: yes

- name: Configuring L2 VNIs for EVPN
  nxos_evpn_vni:
    vni: '{{ item.vni }}'
    route_distinguisher: auto
    route_target_both: auto
  with_items: '{{ tenant_a_l2_vni }}'

- name: Adding BGP configuration
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: 64520
      address_family:
        - afi: ipv4
          safi: unicast
          vrf: tenant_a

- name: Configuring Distributed Anycast Gateway MAC Address on Leaves
  nxos_config:
    lines:
      - fabric forwarding anycast-gateway-mac 0000.0000.000A

- name: Creating SVIs Corresponding to VNIs
  nxos_interfaces:
    config:
      - name: 'vlan {{ item.vlan_id }}'
        enabled: yes
  with_items:
    - '{{ l2_vni_svi_list }}'
    - '{{ l3_vni_svi_list }}'

- name: Adding SVIs to Tenant VRF
  nxos_vrf_interface:
    vrf: '{{ item.vrf }}'
    interface: 'vlan {{ item.vlan_id }}'
  with_items:
    - '{{ l2_vni_svi_list }}'
    - '{{ l3_vni_svi_list }}'

- name: Configuring L2 VNI SVIs with IP addresses
  nxos_l3_interfaces:
    config:
      - name: 'vlan {{ item.vlan_id }}'
        ipv4: 
          - address: '{{ item.ip }}'
  with_items: '{{l2_vni_svi_list }}'

- name: Enabling Anycast Gateway on L2VNI SVIs
  nxos_interfaces:
    config:
      - name: 'vlan {{ item.vlan_id }}'
        fabric_forwarding_anycast_gateway: yes
  with_items: '{{ l2_vni_svi_list }}'

- name: Configuring L3VNI SVI with 'ip forward'
  nxos_interfaces:
    config:
      - name: 'vlan {{ item.vlan_id }}'
        ip_forward: yes
  with_items: '{{ l3_vni_svi_list }}'

# - name: Saving Configuration
#   nxos_config:
#     save_when: changed
