- name: Enabling necessary features
  nxos_feature:
    feature: '{{ item.feature }}'
    state: '{{ item.state }}'
  with_items: '{{ vxlan_features }}'

- name: Enabling EVPN overlay
  nxos_evpn_global:
    nv_overlay_evpn: true

- name: Creating Loopback interfaces to be used as PIM RP and Router-ID
  nxos_interface:
    name: loopback 0-1
    admin_state: up
  ignore_errors: yes

- name: Assigning IP Addresses to the Loopback interfaces
  nxos_l3_interface:
    name: '{{ item.name }}'
    ipv4: '{{ item.ipv4 }}'
  with_items: '{{ loopback_ip }}'

- name: Configuring Leaf Facing Interfaces as L3 and with Jumbo MTU
  nxos_interface:
    name: '{{item.name}}'
    mode: layer3
    mtu: '9216'
    admin_state: up
  with_items: '{{ leaf_facing_ifaces }}'

- name: Configuring Leaf Facing interfaces with IP Unnumbered Parameters
  nxos_config:
    lines:
      - medium p2p
      - ip unnumbered loopback 0
    parents:
      - 'interface {{item.name}}'
  with_items: '{{ leaf_facing_ifaces }}'

- name: Creating OSPF Process 'OSPF_UNDERLAY_NET'
  nxos_ospf_vrf:
    ospf: OSPF_UNDERLAY_NET
    router_id: '{{ router_id }}'

- name: Configuring Leaf Facing Interfaces as OSPF p2p interfaces
  nxos_config:
    lines:
      - ip ospf network point-to-point
    parents:
      - 'interface {{ item.name }}'
  with_items: '{{ leaf_facing_ifaces }}'

- name: Assigning Interfaces to the OSPF Process
  nxos_interface_ospf:
    interface: '{{ item.name }}'
    ospf: OSPF_UNDERLAY_NET
    area: '0'
  with_items:
    - '{{ leaf_facing_ifaces }}'
    - '{{ loopback_ifaces }}'

- name: Configuring PIM RP Addresses
  nxos_pim_rp_address:
    rp_address: '{{ anycast_rp_address }}'
    state: present

- name: Configuring PIM Anycast RP Address
  nxos_config:
    lines:
      -  'ip pim anycast-rp {{ anycast_rp_address }} {{ spine1_loopback0 }}'
      -  'ip pim anycast-rp {{ anycast_rp_address }} {{ spine2_loopback0 }}'

- name: Configuring PIM Sparse Mode on L3 interfaces
  nxos_pim_interface:
    interface: '{{ item.name }}'
    sparse: yes
  with_items:
    -  '{{ leaf_facing_ifaces}}'
    -  '{{ loopback_ifaces }}'

- name: Creating BGP Process
  nxos_bgp:
    asn: '64520'
    router_id: '{{ router_id }}'
    state: present

- name: Configuring Leaves as BGP Neighbors
  nxos_bgp_neighbor:
    asn: '64520'
    neighbor: '{{ item.neighbor }}'
    remote_as: '64520'
    update_source: Loopback0
  with_items: '{{ bgp_leaf_neighbors }}'

- name: Enabling L2VPN EVPN Address-Family Parameters For Leaf Neighbors
  nxos_bgp_neighbor_af:
    asn: '64520'
    neighbor: '{{ item.neighbor }}'
    afi: l2vpn
    safi: evpn
    send_community: both
    state: present
  with_items: '{{ bgp_leaf_neighbors }}'

- name: Enabling IPv4 Unicast Address-Family Parameters For Leaf Neighbors
  nxos_bgp_neighbor_af:
    asn: '64520'
    neighbor: '{{ item.neighbor }}'
    afi: ipv4
    safi: unicast
    send_community: both
    route_reflector_client: yes
    state: present
  with_items: '{{ bgp_leaf_neighbors }}'

# - name: Saving running-configuration...
#   nxos_config:
#     save_when: changed
