- name: Enabling necessary features
  nxos_feature:
    feature: '{{ item.feature }}'
    state: '{{ item.state }}'
  with_items: '{{ vxlan_features }}'

- name: Enabling EVPN overlay
  nxos_evpn_global:
    nv_overlay_evpn: true

- name: Creating Loopback interfaces to be used as PIM RP and Router-ID
  nxos_interfaces:
    config:
      - name: loopback 0-1
        enabled: yes
  ignore_errors: yes

- name: Assigning IP Addresses to the Loopback interfaces
  nxos_l3_interfaces:
    config:
      - name: '{{ item.name }}'
        ipv4: 
          - address: '{{ item.ipv4 }}'
  with_items: '{{ loopback_ip }}'

- name: Configuring Leaf Facing Interfaces as L3 and with Jumbo MTU
  nxos_interfaces:
    config:
      - name: '{{item.name}}'
        mode: layer3
        mtu: '9216'
        enabled: yes
  with_items: '{{ leaf_facing_ifaces }}'

- name: Configuring Leaf Facing interfaces with IP Unnumbered Parameters
  nxos_config:
    lines:
      - medium p2p
      - ip unnumbered loopback 0
    parents:
      - 'interface {{item.name}}'
  with_items: '{{ leaf_facing_ifaces }}'

- name: Creating OSPF Process 'OSPF_UNDERLAY_NET'
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
        - process_id: OSPF_UNDERLAY_NET
          router_id: '{{ router_id }}'

- name: Configuring Leaf Facing Interfaces as OSPF p2p interfaces
  nxos_config:
    lines:
      - ip ospf network point-to-point
    parents:
      - 'interface {{ item.name }}'
  with_items: '{{ leaf_facing_ifaces }}'

- name: Assigning Interfaces to the OSPF Process
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: '{{ item.name }}'
        address_family: 
          - afi: ipv4
            processes: 
              - process_id: OSPF_UNDERLAY_NET
                area:
                  area_id: 0
  with_items:
    - '{{ leaf_facing_ifaces }}'
    - '{{ loopback_ifaces }}'

- name: Configuring PIM RP Addresses
  nxos_pim_rp_address:
    rp_address: '{{ anycast_rp_address }}'
    state: present

- name: Configuring PIM Anycast RP Address
  nxos_config:
    lines:
      -  'ip pim anycast-rp {{ anycast_rp_address }} {{ spine1_loopback0 }}'
      -  'ip pim anycast-rp {{ anycast_rp_address }} {{ spine2_loopback0 }}'

- name: Configuring PIM Sparse Mode on L3 interfaces
  nxos_pim_interface:
    interface: '{{ item.name }}'
    sparse: yes
  with_items:
    -  '{{ leaf_facing_ifaces}}'
    -  '{{ loopback_ifaces }}'

- name: Creating BGP Process
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: 64520
      router_id: '{{ router_id }}'
      neighbors:
        - neighbor_address: '{{ item.neighbor }}'
          remote_as: 64520
          update_source: Loopback0
  with_items: '{{ bgp_leaf_neighbors }}'

- name: Enabling L2VPN EVPN Address-Family Parameters For Leaf Neighbors
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config: 
      as_number: '64520'
      neighbors:
        - neighbor_address: '{{ item.neighbor }}'
          address_family:
            - afi: l2vpn
              safi: evpn
              send_community:
                both: yes
              route_reflector_client: yes
            - afi: ipv4
              safi: unicast
              send_community:
                both: yes
              route_reflector_client: yes
  with_items: '{{ bgp_spine_neighbors }}'

# - name: Saving running-configuration...
#   nxos_config:
#     save_when: changed
