---

  nxos_provider:
    username: "{{ user }}"
    password: "{{ pwd }}"
    transport: nxapi
    host: "{{ inventory_hostname }}"


  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: "nv overlay" }
  - { feature: pim }
  - { feature: interface-vlan }
  - { feature: vnseg_vlan }

  l3_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }
 
  l2_interfaces:
  - { interface: Ethernet1/3 }

 
  ospf_process_id: Underlay

  ospf_area: 0
  
  asn: 64520

  address_families:
  - { afi: l2vpn, safi: evpn }
  - { afi: ipv4, safi: unicast }
  
  bgp_neighbors:
  - { remote_as: 64520, neighbor: 10.201.1.1, update_source: Loopback0 }
  - { remote_as: 64520, neighbor: 10.201.1.2, update_source: Loopback0 }

  rp_address: 100.2.1.1

  vlans_l2vni:
  - { vlan_id: 10, vni_id: 100010, addr: 10.0.11.1, mask: 24, mcast_grp: 224.1.1.192, vrf: Tenant1 }
  - { vlan_id: 20, vni_id: 100020, addr: 10.0.12.1, mask: 24, mcast_grp: 224.1.1.192, vrf: Tenant1 }
  
  vlans_l3vni:
  - { vlan_id: 999, vni_id: 100999, vrf: Tenant1 }

  vrfs:
  - { vrf: Tenant1, vni_id: 100999, afi: ipv4, safi: unicast }
  
